IDEOorg/steps-bot

- .circleci/config.yml
- package.json
Integrate CircleCI to the repository
- integrate CircleCi into the repo
N/A
N/A
#162314792
N/A
N/A
> #162314792 As a developer, i should have confidence that tests in `steps-bot` are run in a CI environment when PRs or merges are performed

- .gitignore
- README.md
- package-lock.json
- package.json
Provide a guide on how to set up the bot to work with localhost
- install ngrok
- add a script for live server
- update README.md
N/A
For Roo developers, access will need to be granted to the Twilio console and the phone number dedicated to the bot for local development has an alias of `Roo_dev`, updating the webhook will have to happen under that number
#162314887
N/A
N/A
> #162314887 As a developer, I should be able to find documentation on how to set up my local environment to work with the `steps-bot` repo

- src/Chatbot.js
- src/Rivebot.js
- src/Updater.js
- src/api.js
- src/constants.js
- tests/e2e.test.js
- Refactors all hardcoded status and topics strings into constants
- Find all instances where values for status and topic are hardcoded
- Define the identified values in the `constants.js` file and replace the hardcoded ones with values from the `constants.js` file
- Clone this repo and checkout to a branch named `ch-move-hard-coded-constants-to-constant-file-162413570`.
- Explore the `src` directory and confirm that there is a file named `constants.js` with `STATUS` and `TOPICS` constants defined there.
- Confirm that no hardcode strings for `status` and `topic` in the other files in `src` directory
Having constants defined in a single file makes it possible to update them when needed rather than having to locate all instances where they have been used to update them. This improves code …
> #162413570 Refactor hardcoded status and topics into a constant file

- .gitignore
- index.js
- src/Chatbot.js
- src/Rivebot.js
- src/Updater.js
- src/api.js
This PR fixes a bug on staging that updates all requests to `RESOLVED`
Add a requestId that only updates a single request to `RESOLVED`
- Login as a coach
- Send multiple help requests from a client
- Reply to one of the requests
- Note only one request is updated
N/A
[#163550996](https://www.pivotaltracker.com/story/show/163550996)
N/A
N/A
> #163550996 As a coach, I should update one request for a task when replying to a client's message

- README.md
- src/Updater.js
- src/email_templates/PmEmail.js
This PR adds functionality to send an email to the Product Manager once a client is sent the "ultimatedone" script by the bot.
Once a user's topic is set to "ultimatedone", an email containing the user's id and messages sent/received by him/her should be sent to the PM's email
- $ git clone https://github.com/IDEOorg/steps-bot.git
- $ cd steps-bot
- $ git checkout ft-send-PM-email-when-ultimatedone-162606983
- $ npm install
- $ npm start
- from the (twiliogui)[http://twilio-gui.herokuapp.com] app reply to the bot with a `B` to complete the task
Initially, no email was sent once a user's status was set to 'ultimatedone'
[#162606983](https://www.pivotaltracker.com/story/show/162606983)
> #162606983 As a PM, I want to receive an email every time a client is sent the "ultimatedone" script by the bot.

- .gitignore
- package-lock.json
- package.json
- src/scheduledUpdater.js
- tests/scheduledUpdater.test.js
This PR creates a script to update `auth0` token on a daily interval
- Add method to get token from auth0
- Add a method to send new token to Heroku
- Add a method to send email to TTL and PM
- Clone the repo
- Switch to the branch `ft-automate-m2m-token-renewal-161304491`
- Run `node src/scheduledUpdater.js`
- A token will be send to the PM email and TTL which are set on environmental variables
N/A
[#161304491](https://www.pivotaltracker.com/story/show/161304491)
N/A
N/A
> #161304491 Automated M2M bot token renewal

- index.js
- package-lock.json
- package.json
- server.js
- src/Messenger.js
- src/api.js
Enable bot to use orgs credentials
- Remove botkit implementation for receiving sms
- Create custom implementation for receiving sms
- Enable bot to fetch org credentials and use it for sending sms
- Add node clusters to enhance bot performance
* Clone this repo
* Checkout to a branch `ft-use-orgs-twilio-sms-credentials-164700316`.
* Run `npm start` and `npm run start:live:dev`
* Setup Twilio webhook.
* Log in as a coach and create a client if not already present.
* Add a task to the client's work plan.
* Visit [twilio-gui](http://twilio-gui.herokuapp.com) and get a phone number.
* login to `twilio-gui`
* Using the direct message feature from the coach app, send a message to the client
* Notice that the client did not receive the message.
**Test For When the credential is provided**
* …
> #164700316 As a bot, I should be able to send text messages with any credentials via Twilio

- .github/PULL_REQUEST_TEMPLATE.md
- scripts/tempfastforward.rive
This PR allows the dev to fast forward to the followup script by sending `followuptopic`. This PR also adds a PR template to the codebase to ease the process of writing Pull Requests.
- add followuptopic to list of tempfastforward commands
- add pull request template
On the terminal, run:
- `git checkout bg-fix-add-followuptopic-to-tempfastforward-165040386`
- `npm start`, open a new console tab and run `npm run start:live:dev`
- Setup the Twilio webhook, select a client and update the client's number
- In the twilio-gui app, send `followuptopic`
- Observe that the followup script is sent to the client.
N/A
[#165040386](https://www.pivotaltracker.com/story/show/165040386)
N/A
> #165040386 Update List of tempfastforward Triggers

- README.md
- index.js
- package-lock.json
- package.json
- server.js
- swagger.yaml
Creates API documentation for API endpoints
- add swagger documentation
- provide relevant API request responses
- update README.md with a link to the API documentation
- $ git clone https://github.com/IDEOorg/steps-bot.git
- $ git checkout ch-document-api-162900982.
- $ npm install
- $ npm start
- visit `http:localhost:3002/api-docs`
- observe that you can see the API documentation
N/A
[#162900982](https://www.pivotaltracker.com/story/show/162900982)
N/A
> #162900982 As a developer, I want up-to-date API documentation for the Bot

- NOTICE
> Creates NOTICE file

- src/Chatbot.js
This PR allows clients with completed workplans to request for followups even when they don't have any pending action items.
- add a check for followup texts
- Checkout to this branch and run `npm run dev`, open a new console tab and run `npm run start:live:dev`
- Setup the Twilio webhook, select a client and complete all the client's tasks
- In the twilio-gui app, send `followuptopic`
- Observe that the `followup` script is sent to the client.
N/A
[#165422678](https://www.pivotaltracker.com/story/show/165422678)
N/A
> #165422678 Allow clients with completed workplans to trigger a follow-up

- package-lock.json
- src/Chatbot.js
- src/Rivebot.js
- src/Updater.js
- src/services/Email.js
- Creates functionality to notify a coach that one of their clients has stopped using the bot
- Create an email template
- Implement functionality to send an email to the coach if the user has sent a `STOP` message
- Clone this repo
- Checkout to a branch `ft-notify-coach-on-stop-message-162638033`.
- Setup Twilio webhook.
- login to `twilio-gui`
- Initiate the conversation with the bot by sending `start`.
- Send a `STOP` message to the bot
- Check that you receive an email on the coach's inbox
[#162638033](https://www.pivotaltracker.com/story/show/162638033)
N/A
> #162638033 As a coach, I want to know if a client has decided to stop using the bot using the "STOP" command

- README.md
> Adds video link to readme

- scripts/checkin.rive
- scripts/help.rive
- scripts/helpcoachresponse.rive
- src/Messenger.js
- src/Rivebot.js
- tests/e2e.test.js
This PR ensures client receives messages ( including magic link) when a coach replies to their test.
- Modify bot script to allow client to get magic link
- Modify bot tests to reflect changes in the bot script
- `git checkout ft-text-client-on-coach-reply-165148192` on steps repo 
- `git checkout ft-text-client-on-coach-reply-165148192` on steps-bot repo
- login as a coach/admin and send a message to a client (Twilio setup should have been done)
- the client receives SMS messages with coach image, coach message and magic link
A client needs to be informed once a coach replies to their query
[#165148192](https://www.pivotaltracker.com/story/show/165148192)
> #165148192 Improved bot script for Coach/Client messaging

- index.js
- utilities/constants.js
- utilities/errorHandler.js
- Handle all errors that are possible within the bot code
- Create an error handler function.
- Implement error handling on async calls.
- Clone this repo
- Checkout to a branch `ft-bot-error-handling-162669895`.
- Create an error by removing the `OAUTH_ACCESS_TOKEN` from the `.env` file.
- Run `npm start` and `npm run start:live:dev`
- Setup Twilio webhook.
- Log in as a coach and create a client if not already present.
- Add a task to the client's work plan.
- Visit [twilio-gui](http://twilio-gui.herokuapp.com) and get a phone number.
- login to `twilio-gui`
- Initiate the conversation with the bot by sending `start`.
- Check the console on your local terminal for the error feedback.
[#162669895](https://www.pivotaltracker.com/story/show/162669895)
PREVIOUS (On Staging)
CURRENTLY (On …
> #162669895 As a developer, I should have confidence that all errors that are possible within the bot code base are being thrown correctly.

- index.js
- src/api.js
This PR checks the Database for clients whose followup_date are due and sends them a follow-up SMS. This check happens every 24 hours.
- add logic to send due followups every 24 hours
- Clone this repo, open the `index.js` file and set the number on line 47 to 1000.
- Setup the Twilio webhook.
- Start the `steps-admin` app and set a follow-up date for any client by following the instructions [here](https://github.com/IDEOorg/steps/pull/604).
- Start the `bot` and observe that your client gets a followup message immediately.
[THIS PR](https://github.com/IDEOorg/steps/pull/604) on the `steps` repo has to be merged for this functionality to work as expected.
[#165680219](https://www.pivotaltracker.com/story/show/165680219)
N/A
> #165680219 Send Due Followup Messages Automatically

- Procfile
- ecosystem.config.js
- package-lock.json
- package.json
Adds a package manager library to the api. The library itself is called PM2.
- Adds PM2 library to the requirements of the bot application.
- The library will restart the application after 3s in the event the application crashes
- clone the repo
- checkout to the branch `ch-integrate-pm2-with-bot-164325658`
- install requirements with `npm install`
- Install `pm2` globally using `npm install --global pm2`.
- Simulate a crash by going to the `index.js` file where the code will execute and add the command `process.exit(1)` on line 25 of the `index.js` file. 
- Run the application using `pm2 start ecosystem.config.js`
- Copy the `ID` field from the result
- Run the command `pm2 logs ID`. `ID` being the value that you copied.
- Notice that the bot crashes and is automatically restarted after …
> #164325658 As a developer, I should have faith that in the event the bot crashes, it is automatically restarted

- src/Updater.js
- src/constants.js
- Refactors checkin times in Updater.js from hardcoded constant values to imported values from a constants file.
- Find all instances where values for check-in times are hardcoded
- Define the identified values in the `constants.js` file and replace the hardcoded ones with imported values
- Clone this repo and checkout to a branch named `ch-update-time-and-frequency-162454156`.
- Find the exported constants in 'constants.js' file. From there the check-in times can be changed. 
[#162454156](https://www.pivotaltracker.com/story/show/162454156)
N/A
N/A
> #162454156 As a developer I should be able to change the frequency and time of day that Roo sends updates in a single location within the bot code.

- src/constants.js
This PR substitutes the video link sent in the `welcomenext` with the most up to date one.
- Change video in `welcomescript` sent by bot to client
1. Clone the repo
2. Checkout to `ch-replace-video-link-in-welcomenext-script-165699583`
3. Run the following commands in Terminal
```bash
npm install
npm start 
npm run start:live:dev #in a separate Terminal window/tab
```
4. Set up Twilio, assign a client the number, and text the keyword `start` from this client.
5. The bot should respond with a message that **includes** the intro video. Verify that this video is the same one specified in this story.
No.
[#165699583](https://www.pivotaltracker.com/story/show/165699583)
N/A
> #165699583 Add the YouTube links for new videos in the right places

- index.js
- package-lock.json
- package.json
- src/Chatbot.js
- src/Rivebot.js
- src/api.js
- src/services/Bitly.js
Modifies the chatLink variable by getting the plan_url from db and replacing 'plan' with 'clientChat'
Retrieve plan_url string from db and use string replace() method to get a chatLink
- `git checkout bg-fix-chaturl-variable-undefined-165853294`
- npm start
- Start the bot 
- Send the keyword "coach"
- Click the link using another browser ( you ought to be redirected to client's views)
ChatLink was undefined for already existing clients.
[#165853294](https://www.pivotaltracker.com/story/show/165853294)
> #165853294 Fix chat_url undefined

- src/Chatbot.js
- tests/e2e.test.js
This PR ensures the bot does not time out when a client has 0 action items.
- Enable sending and receiving of messages for clients with 0 action items.
-`git checkout bg-client-with-no-action-items-165318585`
- npm start
- create a new client
- send the client a message from coach app
- check if you've received message from client side.
Clients with 0 action items were not able to use the bot and their coaches could not send them messages.
[#165318585](https://www.pivotaltracker.com/story/show/165318585)
> #165318585 Bot times out sending/receiving messages for clients with 0 action items
